# -*- coding: utf-8 -*-
"""digital_stress_app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ML_syflsv3L8xobq0y8D0xDe7gWPx8h_
"""

import streamlit as st
import pandas as pd
from datetime import datetime

# ---------- Introduction ----------
st.title("Digital Stress Scale Web App")
st.write("""
**Developer:** Amna Khan – Clinical Psychologist, Researcher, and Data Analyst

Welcome! This bilingual (Urdu + English) app will help you assess your digital stress level.
To proceed to the questionnaire, please complete the $2 payment using the details below.
""")

import streamlit as st

# Introduction Section
st.title("📱 Digital Stress Diagnostic Tool")
st.markdown("""
### Introduction

This tool is based on the **Multidimensional Digital Stressor Scale (MDSS)**.
It is designed **only** for individuals aged **18 to 30 years**.
It diagnoses the **level of digital stress** you may be experiencing due to usage of devices such as mobile phones, laptops, and social media.

⚠️ **Important Notes:**
- This tool specifically measures **digital stress**, not other types of stress.
- It does **not** assess professional or work-related stress caused by using devices for your job or study.
- Please answer all questions honestly based on your experience in the **past 7 days**.
- While it is a diagnostic tool for digital stress, it should be used for **awareness and guidance**, not as a substitute for professional medical or psychological evaluation.

Click **Next** to start the questionnaire.
""")

# Add a "Next" button to go to questions
if st.button("Next ➡️"):
    st.session_state.page = "questions"


# ---------- Part 1: Sample Questions ----------
st.subheader("Sample Questions")

sample_items = [
    ("Most of my friends approve of me being constantly available online",
     "میرے زیادہ تر دوست میرے مسلسل آن لائن رہنے سے متفق ہیں"),
    ("I feel a social obligation to be constantly available online",
     "مسلسل آن لائن رہنا مجھے ایک سماجی ذمہ داری محسوس ہوتا ہے")
]

scale_labels = ["0 - Strongly Disagree", "1 - Disagree", "2 - Neutral", "3 - Agree", "4 - Strongly Agree"]

for idx, item in enumerate(sample_items, 1):
    st.markdown(f"**Q{idx}. {item[0]}**  \n_{item[1]}_")
    st.radio("", scale_labels, key=f"sample_{idx}")

# ---------- Part 2: Payment Section ----------
st.subheader("Unlock Full Assessment")

st.write("""
**How to Make Payment (EasyPaisa):**  
1. Send the payment via the EasyPaisa app or a nearby agent.  
2. Use this number to send the payment: **03068732970**  
3. After payment, you will receive a **confirmation code** via SMS.  
4. Enter that code in the field below to unlock the full assessment.
""")

# Payment code input
payment_code = st.text_input("Enter your EasyPaisa payment confirmation code:")

# Simple code verification (example: "1234" is valid)
valid_codes = ["1234", "5678", "91011"]  # Replace with your real codes

if payment_code:
    if payment_code in valid_codes:
        st.success("Payment verified! You can now access the full assessment.")
        # Show full assessment content here
    else:
        st.error("Invalid code. Please check your SMS and enter the correct code.")

# ---------- Part 3: Full Assessment (Locked) ----------
if payment_code == "PAID123":  # Replace with your actual payment code
    st.success("Payment verified! Full assessment unlocked.")

    digital_stress_items = [
        {"id": 1, "en_text": "Most of my friends approve of me being constantly available online", "ur_text": "میرے زیادہ تر دوست میرے مسلسل آن لائن رہنے سے متفق ہیں"},
        {"id": 2, "en_text": "I feel a social obligation to be constantly available online", "ur_text": "مسلسل آن لائن رہنا مجھے ایک سماجی ذمہ داری محسوس ہوتا ہے"},
        {"id": 3, "en_text": "I am nervous about how people will respond to my posts and photos", "ur_text": "میں پریشان ہوتا ہوں کہ لوگ میرے پوسٹ اور تصویر کا کس طرح سے جواب دیں گے؟"},
        {"id": 4, "en_text": "I feel anxious about how others will respond when I share a new photo on social media", "ur_text": "میری طرف سے سوشل میڈیا پر کوئی نئی تصویر شیئر کی جاتی ہے تو مجھے بیچینی ہوتی ہے کہ دوسرے کیسے جواب دیں گے؟"},
        {"id": 5, "en_text": "I feel nervous after I share a post or photo to see how others responded to it", "ur_text": "مجھے پوسٹ یا تصویر کو شیئر کرنے کے بعد گھبراہٹ محسوس ہوتی ہے کہ دوسروں نے اس پر کیا ردعمل دیا ہوگا؟"},
        {"id": 6, "en_text": "I feel nervous about how others will respond when I post new updates on social media", "ur_text": "مجھے پریشانی محسوس ہوتی ہے کہ لوگ میرے تازہ ترین پوسٹ پر کیسے جواب دیں گے؟"},
        {"id": 7, "en_text": "I put a lot of effort into finding or creating a photo that others will approve of when I post it online", "ur_text": "مجھے آن لائن پوسٹ کرنے کے لیے تصویر ڈھونڈنے اور بنانے میں بہت کوشش کرنی پڑتی ہے تاکہ دوسروں کی منظوری مل سکے"},
        {"id": 8, "en_text": "I put a lot of effort into composing messages and posts I share online", "ur_text": "مجھے اُن پیغامات اور پوسٹ کو تیار کرنے میں بہت محنت درکار ہوتی ہے جو میں آن لائن شیئر کرتا ہوں۔"},
        {"id": 9, "en_text": "I fear my friends are having more rewarding experiences than me", "ur_text": "مجھے ڈر ہے کہ میرے دوستوں کے مجھ سے زیادہ خوشگوار تجربات ہیں"},
        {"id": 10, "en_text": "I fear that others have more rewarding experiences than me", "ur_text": "مجھے لگتا ہے کہ دوسروں کے مجھ سے زیادہ تسکین آور تجربات ہیں"},
        {"id": 11, "en_text": "I get worried when I find out my friends are having fun without me", "ur_text": "مجھے پریشانی ہوتی ہے جب مجھے معلوم ہوتا ہے کہ میرے دوست میرے بغیر مزہ کر رہے ہیں"},
        {"id": 12, "en_text": "I get anxious when I don’t know what my friends are up to", "ur_text": "مجھے پریشانی ہوتی ہے جب مجھے معلوم نہیں ہوتا کہ میرے دوست کیا کر رہے ہیں"},
        {"id": 13, "en_text": "I have to check too many notifications", "ur_text": "مجھے بہت زیادہ اطلاعات دیکھنی پڑتی ہیں"},
        {"id": 14, "en_text": "I feel overwhelmed with the flow of messages/notifications on my phone", "ur_text": "مجھے اپنے فون پر پیغامات اور اطلاعات کے مسلسل بہاؤ سے بے انتہا دباؤ محسوس ہوتا ہے"},
        {"id": 15, "en_text": "It feels like there is always a reminder—like a flashing light or buzz—that there is some other message that I need to attend to", "ur_text": "چمکتی روشنی یا بھنبناہٹ سے ایسا محسوس ہوتا ہے کہ کوئی دوسرا پیغام ہے جو مجھے دیکھنا ضروری ہے"},
        {"id": 16, "en_text": "I feel stress because I must sift through a lot of unimportant notifications to get to the important ones", "ur_text": "میں تناؤ محسوس کرتا ہوں کیونکہ مجھے اہم اطلاع تک پہنچنے کے لیے بہت ساری غیر اہم اطلاعات کو جانچنا پڑتا ہے۔"},
        {"id": 17, "en_text": "On top of the other things I must do, keeping up with notifications is a chore", "ur_text": "دیگر اہم کاموں کے ساتھ ساتھ اطلاعات دیکھنا بھی ایک کام ہے"},
        {"id": 18, "en_text": "I spend too much time responding to notifications/messages", "ur_text": "مجھے پیغامات کا جواب دینے میں بہت زیادہ وقت لگتا ہے"},
        {"id": 19, "en_text": "I must have my phone with me to know what is going on", "ur_text": "یہ جاننے کے لیے کہ کیا چل رہا ہے، میرے پاس میرا فون ہونا ضروری ہے"},
        {"id": 20, "en_text": "I feel lost or 'naked' without my phone", "ur_text": "مجھے فون کے بغیر کھویا ہوا یا خالی محسوس ہوتا ہے۔"},
        {"id": 21, "en_text": "I am constantly checking my phone for messages/notifications", "ur_text": "میں مسلسل اپنے فون پر پیغامات یا اطلاعات دیکھتا ہوں"},
        {"id": 22, "en_text": "I feel socially unavailable when I do not have my phone", "ur_text": "جب میرے پاس میرا فون نہیں ہوتا تو میں سماجی طور پر خود کو غیر دستیاب محسوس کرتا ہوں۔"}
    ]

    responses = []
    for item in digital_stress_items:
        st.markdown(f"**Q{item['id']}. {item['en_text']}**  \n_{item['ur_text']}_")
        score = st.radio("", scale_labels, key=f"q{item['id']}")
        responses.append(int(score.split(" - ")[0]))

    if st.button("Submit Full Assessment"):
        total_score = sum(responses)
        st.write(f"Your total digital stress score is: {total_score}")

        # Categorize stress level
        if total_score <= 21:
            st.write("Low digital stress")
        elif total_score <= 44:
            st.write("Moderate digital stress")
        elif total_score <= 66:
            st.write("Elevated digital stress")
        else:
            st.write("High digital stress")
else:
    st.info("Full assessment is locked. Complete payment to get the code and unlock it.")
     